info:
  contact: {}
  description: Notify when water level is low
  title: SensorSentinel
  version: "2.0"
paths:
  /health:
    get:
      description: Get the health of the application
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      summary: Get health
      tags:
      - health
swagger: "2.0"
